<?php
  $page_title = 'Student Table';
  include('../includes/header.html');
?>

<table style="width:80%">
  <tr>
    <th>Student ID</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>
  <tr>
    <td>001</td>
    <td>John</td>
    <td>Cusack</td>
    <td>jcusack@email.com</td>
    <td>(123)456-7890</td>
  </tr>
  <tr>
    <td>002</td>
    <td>Phil</td>
    <td>Jackson</td>
    <td>pjackson@mail.net</td>
    <td>(299)123-4567</td>
  </tr>
  <tr>
    <td>003</td>
    <td>Ricardo</td>
    <td>Tubbs</td>
    <td>rtmv@email.com</td>
    <td>(765)432-1098</td>
  </tr>
  <tr>
    <td>004</td>
    <td>Julianne</td>
    <td>Moore</td>
    <td>jmoore@mail.com</td>
    <td>(234)656-7854</td>
  </tr>
  <tr>
    <td>005</td>
    <td>Pedro</td>
    <td>Martinez</td>
    <td>pmar@email.mail</td>
    <td>(444)765-8954</td>
  </tr>
  <tr>
    <td>006</td>
    <td>Ellen</td>
    <td>Ripley</td>
    <td>eripley@neutronmail.com</td>
    <td>(567)890-1112</td>
  </tr>
  <tr>
    <td>007</td>
    <td>James</td>
    <td>Bond</td>
    <td>jamesbond007@mail.com</td>
    <td>(687)684-9128</td>
  </tr>
  <tr>
    <td>008</td>
    <td>Leroy</td>
    <td>Brown</td>
    <td>lbrown@odyssey.mail</td>
    <td>(333)333-4567</td>
  </tr>
  <tr>
    <td>009</td>
    <td>Marco</td>
    <td>Reus</td>
    <td>mreus@mail.com</td>
    <td>(987)654-3210</td>
  </tr>
  <tr>
    <td>010</td>
    <td>Kevin</td>
    <td>Bacon</td>
    <td>kbacon@mail.com</td>
    <td>(677)321-1234</td>
  </tr>
  <tr>
    <td>011</td>
    <td>Nathalie</td>
    <td>Merchant</td>
    <td>nmerch@email.com</td>
    <td>(222)908-8876</td>
  <tr>
</table>

<?php
  include('../includes/footer.html');
?>
